$ErrorActionPreference = 'Stop'
$env:AI_CHAT_BASE_URL = 'http://localhost:18080'
$env:AI_CHAT_API_KEY = 'agentops-dev-key'
$env:AI_CHAT_PROVIDER = 'openai'
$env:AI_CHAT_MODEL = 'deterministic-fund-model'
$env:FUND_AGENT_ENABLED = 'true'
$env:FUND_AGENT_PROMPT_VERSION = 'fund-agent-v1'
$env:FUND_KNOWLEDGE_ENABLED = 'true'
$env:AGENTOPS_PROMPT_ENABLED = 'true'
$env:AGENTOPS_BASE_URL = 'http://localhost:18080'
$env:MYSQL_URL = 'jdbc:mysql://localhost:13306/jijing_agent?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai'
$env:MYSQL_USERNAME = 'agentops'
$env:MYSQL_PASSWORD = 'agentops'
$env:REDIS_HOST = 'localhost'
$env:REDIS_PORT = '16379'
$env:SERVER_PORT = '18081'
$env:FUND_JWT_SIGNING_KEY = 'agentops-local-eval-signing-key-32-bytes-minimum'
$env:SPRING_PROFILES_ACTIVE = 'local,agent-eval'
# The explicit project settings avoid relying on a machine-global Maven mirror.
mvn -gs D:\jijing-agent\.mvn\settings-global-public.xml -f D:\jijing-agent\pom.xml -pl fund-bootstrap -am spring-boot:run
